---
version: '2'
services:
  # BASIC SERVICES
  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - mosquitto_data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
  mqtt-logger:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    network_mode: host
    entrypoint: "/usr/bin/mosquitto_sub"
    command: [ "-h", "localhost", "-F", "%I: %t: %p", "-t", "#" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
  bridge:
    image: automatedhome/evok-mqtt-bridge
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mosquitto
  evokmapper:
    image: automatedhome/mqttmapper
    restart: unless-stopped
    network_mode: host
    depends_on: 
      - mosquitto 
      - bridge
    volumes:
      - "${PWD}/evokmapping.yml:/config.yaml"
      - /etc/localtime:/etc/localtime:ro
    command: [ "-clientid", "evokmapper" ]

  # Periodic synchroniser, should be removed when system gets stable
  synchroniser:
    image: automatedhome/evok-synchroniser
    restart: unless-stopped
    network_mode: host
    depends_on: 
      - mosquitto 
      - bridge

  # SENSORS
  flow-meter:
    image: automatedhome/flow-meter
    restart: unless-stopped
    network_mode: host
    depends_on:
      - synchroniser
      - mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: ["-outTopic", "solar/flow/value"]
  analog-in:
    image: automatedhome/analog-temperature
    restart: unless-stopped
    network_mode: host
    depends_on:
      - synchroniser
      - mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
  roomtemp:
    image: automatedhome/roomtemp
    restart: unless-stopped
    network_mode: host
    depends_on:
      - synchroniser
      - mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # CONTROLLERS
  scheduler:
    image: automatedhome/scheduler
    restart: unless-stopped
    network_mode: host
    depends_on: 
      - bridge
      - mosquitto
    command: ["-topic", "heater/settings/schedule"]
  solar:
    image: automatedhome/solar
    restart: unless-stopped
    network_mode: host
    depends_on: 
      - mosquitto 
      - bridge
      - evokmapper
  heater:
    image: automatedhome/heater
    restart: unless-stopped
    network_mode: host
    depends_on: 
      - mosquitto 
      - bridge
      - evokmapper
  circulation:
    image: automatedhome/circulation
    restart: unless-stopped
    network_mode: host
    depends_on: 
      - mosquitto 
      - bridge
      - evokmapper
    command: ["-inTopic", "evok/input/5/value", "-outTopic", "evok/relay/4/set"]
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  mosquitto_data:
