# RMEOVE AFTER MIGRATION TO HA
# Run against remote (HMI) broker 
topics:
- in: "solarControl/circulate/settings/interval"
  out: "unipi/circulation/settings/interval"
  retained: true
- in: "solarControl/circulate/settings/time_on"
  out: "unipi/circulation/settings/duration"
  retained: true

- in: "solarControl/heater/settings/critical"
  out: "unipi/heater/settings/critical"
  retained: true
- in: "solarControl/heater/settings/hysteresis"
  out: "unipi/heater/settings/hysteresis"
  retained: true
- in: "solarControl/tank/settings/heater_min"
  out: "unipi/heater/settings/tankmin"
  retained: true
- in: "solarControl/tank/settings/heater_max"
  out: "unipi/heater/settings/tankmax"
  retained: true

- in: "solarControl/solar/settings/critical"
  out: "unipi/solar/settings/critical"
  retained: true
- in: "solarControl/solar/settings/temp_on"
  out: "unipi/solar/settings/on"
  retained: true
- in: "solarControl/solar/settings/temp_off"
  out: "unipi/solar/settings/off"
  retained: true
- in: "solarControl/tank/settings/solar_max"
  out: "unipi/solar/settings/tank"
  retained: true
#- in: ""
#  out: "unipi/solar/settings/flow/t_min"
#  retained: true
#- in: ""
#  out: "unipi/solar/settings/flow/t_max"
#  retained: true
#- in: ""
#  out: "unipi/solar/settings/flow/d_min"
#  retained: true
#- in: ""
#  out: "unipi/solar/settings/flow/d_max"
#  retained: true

- in: "solarControl/heater/settings/expected"
  out: "unipi/heater/settings/override"
#- in: ""
#  out: "unipi/heater/settings/holiday"
#  retained: true

